default_config:

homeassistant:
  #external_url: http://192.168.1.201:9124
  #internal_url: http://192.168.1.64:8123


stream:


logger:
  default: info
  logs:
    custom_components.motion_frontend: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
