default_config:

stream:

logger:
  default: info
  logs:
    custom_components.motion_frontend: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
